import Head from 'next/head'
import Navigation from '../komponenten/Navigation'
import Footer from '../komponenten/Footer'


export default function Layout({children}) {
  return (
    <div>
      <Head>
        <title>Liefermax - Dein Lieferservice</title>
        <meta name="description" content="Generated by medianasoft.de" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navigation />
    <div className='container'>
        {children}
    </div>
    <Footer />
    </div>
  )
}